# Generated by Django 3.2.5 on 2021-11-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asociados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='asociados')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='asociados')),
            ],
        ),
    ]
