# Generated by Django 3.2.5 on 2021-11-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonios',
            name='imagen',
            field=models.ImageField(null=True, upload_to='testimonios'),
        ),
    ]
