# Generated by Django 3.1.2 on 2021-11-20 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tipoaso'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociados',
            name='TipoAsociado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipoaso'),
            preserve_default=False,
        ),
    ]
