# Generated by Django 3.1.2 on 2021-11-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_clientesasesorados'),
    ]

    operations = [
        migrations.CreateModel(
            name='informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=250)),
                ('correo', models.EmailField(max_length=254)),
                ('logo_nav', models.ImageField(null=True, upload_to='Navbar')),
                ('lofo_footer', models.ImageField(null=True, upload_to='Footer')),
                ('mision', models.TextField(max_length=235)),
                ('vision', models.TextField(max_length=235)),
                ('facebook', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('youtube', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('url_maps', models.TextField(max_length=600)),
                ('url_video', models.TextField(max_length=200)),
            ],
        ),
    ]
