# Generated by Django 3.1.2 on 2021-11-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211121_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='url_maps',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='url_video',
            field=models.CharField(max_length=200),
        ),
    ]
