# Generated by Django 3.1.2 on 2021-11-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211121_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='informacion',
            name='intro_nosotros',
            field=models.TextField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.blog_index'),
        ),
    ]
