# Generated by Django 3.1.2 on 2021-11-21 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211121_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='lugar',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.blog_index'),
        ),
    ]
