# Generated by Django 3.1.2 on 2021-11-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211121_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociados',
            name='slug',
            field=models.SlugField(default=1, max_length=150, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=1, max_length=150, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
