# Generated by Django 3.1.2 on 2021-11-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211123_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='nombre',
            field=models.CharField(default=1, max_length=150, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
