# Generated by Django 3.1.2 on 2021-11-23 22:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211123_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Titulo')),
                ('descripcion', models.TextField(max_length=150, verbose_name='Descripcion')),
                ('imagen', models.ImageField(null=True, upload_to='carrusel')),
            ],
        ),
        migrations.AlterField(
            model_name='asociados',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', ckeditor.fields.RichTextField(max_length=150, verbose_name='Titulo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asociados')),
            ],
        ),
    ]
