# Generated by Django 3.1.2 on 2021-11-24 04:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211123_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociados',
            name='vida',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frase',
            name='nombre',
            field=ckeditor.fields.RichTextField(max_length=600, verbose_name='Frase'),
        ),
    ]
