# Generated by Django 3.1.2 on 2021-11-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211123_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('icon', models.ImageField(null=True, upload_to='services_icon')),
                ('imagen', models.ImageField(null=True, upload_to='services')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, verbose_name='Slug')),
            ],
        ),
    ]
