# Generated by Django 3.1.2 on 2021-11-24 18:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
