# Generated by Django 3.1.2 on 2022-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_service_icon_white'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociados',
            name='nombre_corto',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
