# Generated by Django 3.1.2 on 2022-02-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_informacion_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='sectoresAsesorados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to='sectores')),
            ],
        ),
    ]
