# Generated by Django 3.1.2 on 2022-02-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_sectoresasesorados'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociados',
            name='correo',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asociados',
            name='linkedin',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
