# Generated by Django 3.1.2 on 2022-02-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20220225_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='descripcion',
            field=models.TextField(max_length=150, null=True, verbose_name='Descripcion'),
        ),
    ]
