# Generated by Django 3.1.2 on 2022-02-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20220226_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='descripcion',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Descripcion'),
        ),
    ]
