# Generated by Django 3.1.2 on 2022-03-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20220306_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='info',
            field=models.TextField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
