# Generated by Django 3.1.2 on 2022-03-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_landing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
